#!/usr/bin/env python3
"""Generate -pro variants of SDLC agents for Cursor tiered routing.

Pro variants are byte-identical to base agents EXCEPT for:
- frontmatter `name:` → appends `-pro`
- frontmatter `model:` → set to escalation-tier model
- one extra description sentence flagging it as escalation tier

Run: python make-pro-agents.py [--check]
  --check : verify pro files are in sync with base (exit 1 if drift)

Re-run after editing any base agent file to keep pro variants synced.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Tier mapping per dispatcher.md § Tiered Routing
PRO_MAPPING = {
    "dev": "claude-opus-4-7",
    "qa": "claude-opus-4-7",
    "reviewer": "claude-opus-4-7",
    "sa": "claude-opus-4-7",
    "ba": "claude-opus-4-7",
}

PRO_NOTE = (
    "\n\n> **ESCALATION TIER**: This is the `-pro` variant invoked by dispatcher when "
    "base agent returns `confidence: low` or stage triggers force-escalation "
    "(e.g., risk_score ≥ 3 for reviewer, adr_id assigned for sa, risk_score ≥ 4 for ba, "
    "test failure rate > 30% for dev, ac_coverage_pct < 80 for qa). "
    "Same prompt body + role discipline as base; only `model:` frontmatter differs. "
    "Generated by `~/.cursor/skills/cache-lint/make-pro-agents.py` — do not edit directly. "
    "Edit `{base}.md` and re-run script.\n"
)


def transform(base_text: str, role: str, pro_model: str) -> str:
    """Convert base agent text → pro variant."""
    lines = base_text.split("\n")
    if not lines or lines[0].strip() != "---":
        raise ValueError(f"{role}: missing frontmatter")

    fm_end = next((i for i in range(1, len(lines)) if lines[i].startswith("---")), -1)
    if fm_end < 0:
        raise ValueError(f"{role}: unterminated frontmatter")

    new_lines = ["---"]
    for line in lines[1:fm_end]:
        if line.startswith("name:"):
            new_lines.append(f"name: {role}-pro")
        elif line.startswith("model:"):
            new_lines.append(f"model: {pro_model}")
        elif line.startswith("description:"):
            # Append escalation marker to description
            desc = line[len("description:"):].strip()
            new_lines.append(
                f"description: [ESCALATION TIER — opus] {desc}"
            )
        else:
            new_lines.append(line)
    new_lines.append("---")

    body = "\n".join(lines[fm_end + 1:])
    note = PRO_NOTE.format(base=role)
    return "\n".join(new_lines) + note + body


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--check", action="store_true",
                   help="Verify pro files in sync; exit 1 if drift")
    args = p.parse_args()

    agents_dir = Path("~/.cursor/agents").expanduser()
    drift = []
    written = []

    for role, pro_model in PRO_MAPPING.items():
        base_path = agents_dir / f"{role}.md"
        pro_path = agents_dir / f"{role}-pro.md"

        if not base_path.exists():
            print(f"[SKIP] {role}.md not found")
            continue

        base_text = base_path.read_text(encoding="utf-8").replace("\r\n", "\n")
        expected = transform(base_text, role, pro_model)

        if args.check:
            if not pro_path.exists():
                drift.append(f"{role}-pro.md: MISSING")
            elif pro_path.read_text(encoding="utf-8") != expected:
                drift.append(f"{role}-pro.md: DRIFT (run without --check to regenerate)")
        else:
            if pro_path.exists() and pro_path.read_text(encoding="utf-8") == expected:
                continue  # already in sync
            pro_path.write_bytes(expected.encode("utf-8"))
            written.append(str(pro_path))

    if args.check:
        if drift:
            for d in drift:
                print(f"[DRIFT] {d}")
            return 1
        print(f"[OK] All {len(PRO_MAPPING)} pro agents in sync")
        return 0

    for w in written:
        print(f"[WROTE] {w}")
    print(f"\n[INFO] Generated {len(written)}/{len(PRO_MAPPING)} pro agents")
    return 0


if __name__ == "__main__":
    sys.exit(main())
